### ISSUE TITLE
Extension doesn't work

### ISSUE THREAD

**Issue by acidline** [serweb-labs/bolt-rest-api#1]
Hi,

It's seems that extension doesn't work on Bolt 3.2.13
I think that the base config.yml.dist is not complete.
I have errors in the RestController because some config keys aren't defined.

```php
// readMultipleContentAction & readContentAction
$isSoft = $this->config['delete']['soft'];
$softStatus = $this->config['delete']['status'];
```
Can you explain what is these config parts ?

Moreover, 
```php
// readMultipleContentAction 
if (array_key_exists('only_published', $this->config) && $this->config['only_published']) {
    $status = "published";
}
```
instead of 
```php
// readMultipleContentAction 
if ($this->config['only_published']) {
    $status = "published";
}
```
==> throw an Error

Thank's for your answer and your time.

Nicolas

**Comment by serweb-labs** [comment]
sorry, missing configurations.
fix in 954be66820b75dbd398579f0ff7aa8ef730fb174
