### ISSUE TITLE
Cannot login with jwt

### ISSUE THREAD

**Issue by MeStrak** [serweb-labs/bolt-rest-api#9]
Using the curl command provided in the readme, some other variations, I can't authenticate at all.

Here's the sample command from the readme (obviously I replaced example.com, myuser and mypass with my domain and username/password settings from the extension config file:
`curl -X POST -H "https://example.com/auth/login?username=myuser&password=mypass"`
I get the response: **curl: no URL specified!**

When I remove the - H:
`curl -X POST "https://example.com/auth/login?username=myuser&password=mypass"`
The following HTML is returned:
`<title>Access Denied</title>
</head>
<body>
<div class="centered">
        <div class="container">
                <div class="header">
                        <h1>The page you are trying to access is restricted due to a security rule.</h1>
        <br>
                        <h2>If you believe the security rule is affecting the normal operation of your website, contact your host support team and provide detailed instructions how to recreate this error.
<br>
They will be able to assist you with rectifying the problem and adjusting the security configuration if needed.</h2>
                </div>
        </div>
</div>
</body>`

When I visit the url directly in Google Chrome I get this error:
**MethodNotAllowedHttpException in RouterListener.php line 183: 
No route found for "GET /auth/login": Method Not Allowed (Allow: POST, OPTIONS)**

Are there some configuration steps missing from the readme?

Thanks,
Strak

**Comment by genepool99** [comment]
Looks like you are running the ModSecurity module. In your .htaccess try adding
```
<IfModule mod_security.c>
  SecFilterEngine Off
  SecFilterScanPOST Off
</IfModule>
```
Then run the command:
`curl -X POST "http://example.com/auth/login?username=username&password=password" -v` and it should show the X-Access-Token header.
